### DISCUSSION TITLE
Using content folder with config

### DISCUSSION THREAD

**Discussion by UrieW** [devcows/hugo-universal-theme#427] [Q&A]
I made a file tree in content to match the menu in config.yml of my
site using Universal. Here is the tree:

```
content
│   albums.md
│   contact.md
│   demos.md
│   gallery.md
│   home.md
│   map.md
│
├───about
│       faqs.md
│       links.md
│       our-history.md
│       our-purpose.md
│       toc.md
│
├───blog
└───shop
```

Now here's the config file's version of it:

```
menu:
  main:
    - name: Home
      identifier: menu.home
      url: /
      weight: 1
    - name: 'Gallery'
      url: /
      weight: 1
      parent: menu.home
    - name: 'Theater'
      url: /
      weight: 2
      parent: menu.home
    - name: 'Albums'
      url: /
      weight: 3
      parent: menu.home
    - name: 'Demos'
      url: /
      weight: 4
      parent: menu.home
    - name: Blog
      identifier: menu.blog
      url: /blog/
      weight: 2
    - name: Shop
      identifier: menu.shop
      url: /shop/
      weight: 3
    - name: About
      identifier: menu.about
      url: /about/
      weight: 4
    - name: Our History
      identifier: section.a-history
      url: ''
      weight: 1
      parent: menu.about
    - name: Our Purpose
      identifier: section.a-purpose
      url: ''
      weight: 2
      parent: menu.about
    - name: ToC
      identifier: section.a-toc
      url: ''
      weight: 3
      parent: menu.about
    - name: FAQs
      identifier: section.a-faqs
      url: ''
      weight: 4
      parent: menu.about
    - name: Links
      identifier: section.a-links
      url: ''
      weight: 5
      parent: menu.about
    - name: Map
      identifier: menu.map
      url: /map/
      weight: 5
    - name: Home
      identifier: section.ap-home
      url: ''
      weight: 1
      parent: menu.map
    - name: Gallery
      identifier: section.ap-gallery
      url: ''
      weight: 2
      parent: menu.map
    - name: Theater
      identifier: section.ap-theater
      url: ''
      weight: 3
      parent: menu.map
    - name: Albums
      identifier: section.ap-albums
      url: ''
      weight: 4
      parent: menu.map
    - name: Demos
      identifier: section.ap-demos
      url: ''
      weight: 5
      parent: menu.map
    - name: Blog
      identifier: section.ap-blog
      url: ''
      weight: 1
      parent: menu.map
    - name: Shop
      identifier: section.ap-shop
      url: ''
      weight: 1
      parent: menu.map
    - name: About
      identifier: section.ap-about
      url: ''
      weight: 1
      parent: menu.map
    - name: Our History
      identifier: section.ap-history
      url: ''
      weight: 2
      parent: menu.map
    - name: Our Purpose
      identifier: section.ap-purpose
      url: ''
      weight: 3
      parent: menu.map
    - name: ToC
      identifier: section.ap-toc
      url: ''
      weight: 4
      parent: menu.map
    - name: FAQs
      identifier: section.ap-faqs
      url: ''
      weight: 5
      parent: menu.map
    - name: Links
      identifier: section.ap-links
      url: ''
      weight: 6
      parent: menu.map
    - name: Contact
      identifier: contact
      url: /contact/
      weight: 6
```

Am I doing it right?
