### ISSUE TITLE
How to set up a submenu?

### ISSUE THREAD

**Issue by heavenzone** [devcows/hugo-universal-theme#148]
Thanks for the excellent theme. But I have a question that how to make a submenu.

I had took a look at the source code here:

```html
<div class="navbar-collapse collapse" id="navigation">
	<ul class="nav navbar-nav navbar-right">
	  {{ range .Site.Menus.main }}
	  <li class="dropdown">
		{{ if .HasChildren }}
		  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ .Name }} <span class="caret"></span></a>
		<ul class="dropdown-menu">
		  {{ range .Children }}
			<li><a href="{{ .URL }}">{{ .Name }}</a></li>
		  {{ end }}
		</ul>
		{{ else }}
		<a href="{{ .URL }}">{{ .Name }}</a>
		{{ end  }}
	  </li>
	  {{ end }}
	</ul>
</div>
<!--/.nav-collapse -->
```

I don't know how to set up the submenu for the `.Children` variable.

I tried to do this:

```toml
[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier = "brand"
    name = "brand"
    url = "/brands/"
    weight = 2
    
[[menu.main.brands]]
    name = "brand1"
    url = "/brands/"
    weight = 2

[[menu.main.brands]]
    name = "brand2"
    url = "/brands/"
    weight = 3
    
    
[[menu.main]]
    name = "product"
    url = "/product/"
    weight = 2
```

But it doesn't work. Could somebody help?
