### ISSUE TITLE
Example for Dropdown Menu of universal template

### ISSUE THREAD

**Issue by kingedwords** [devcows/hugo-universal-theme#34]
I don't have an idea how to create dropdown menus in hugo. Universal supports dropdown-menus. Does anyone have an idea?

**Comment by adrianmo** [comment]
@kingedwords, event though the original Universal theme supports dropdown menus, this port has not implemented this feature yet. I encourage you to do it and submit a PR for us to review and help you out with the implementation.

**Comment by schuster-rainer** [comment]
@kingedwords My pull request #51 will add submenus.

this will allow you the features from hugo https://gohugo.io/extras/menus/

In order to have have a submenu add identifier="<name>" to the menu item which should act as top menu and parent="<name>" to the child menu items.

```toml
  [[menu.main]]
    Name = "Teams"
    identifier = "teams"
    URL = "#"
    Weight = 1.0

  [[menu.main]]
    Name = "Team 1"
    parent = "teams"
    URL = "/teams/team1.md"
    Weight = 1.0

  [[menu.main]]
    Name = "Team 2"
    parent = "teams"
    URL = "/teams/team2.md"
    Weight = 2.0
```

or just paste the menu in the frontmatter as described on the hugo help about menus.

For this to work after the merge has been accepted into master you have to refactor your menu from `[[params.menu]]` to `[[menu.main]]`.
