### ISSUE TITLE
Premium to remove footer watermark

### ISSUE THREAD

**Issue by biden2020prez** [devcows/hugo-universal-theme#383]
Is there any option to donate or buy a premium and remove the DevCows watermark in the footer?

**Comment by Xenion1987** [comment]
https://github.com/devcows/hugo-universal-theme/blob/cf0336a1758491e3375358d59f8bc64065f6d75b/layouts/partials/footer.html#L80C15-L80C125
`<!-- Not removing this link is part of the licence conditions of the template. Thanks for understanding :) -->`

It is not allowed to remove the link. But it is not forbidden to change the font's colors (maybe pink color on pink background)

**Comment by biden2020prez** [comment]
> 

Hehe I was wondering that

**Comment by Xenion1987** [comment]
In my case I've set the color to the same color as the footer background:
```css
.pull-right,
.pull-right a {
    color: #333;
}
```
Setting the `font-size` to `0px` would also work:
```css
.pull-right,
.pull-right a {
    font-size: 0px;
}
```
Or setting `visibility` to `hidden`:
```css
.pull-right,
.pull-right a {
    visibility: hidden;
}
```
