### ISSUE TITLE
Custom Icons

### ISSUE THREAD

**Issue by ghost** [devcows/hugo-universal-theme#433]
For the icons in the features area of the home page, how can I use static files for some of the icons and font awesome icons for others?

I tried
```yaml
weight: 1
name: "Servers"
icon: /img/icons/server.png
url: ""
description: "We design custom servers."
```
however the bubble is just blank now

The file path can be visited directly and is valid
